export const skillIconUrls: Record<string, string> = {
  Angular: "/tech-icons/angular-original.svg",
  AWS: "/tech-icons/amazonwebservices-original-wordmark.svg",
  "Azure DevOps": "/tech-icons/azuredevops-original.svg",
  Docker: "/tech-icons/docker-original.svg",
  Flask: "/tech-icons/flask-original.svg",
  GCP: "/tech-icons/googlecloud-original.svg",
  Java: "/tech-icons/java-original.svg",
  JavaScript: "/tech-icons/javascript-original.svg",
  Kafka: "/tech-icons/apachekafka-original.svg",
  Kubernetes: "/tech-icons/kubernetes-original.svg",
  MongoDB: "/tech-icons/mongodb-original.svg",
  "Next.js": "/tech-icons/nextjs-original.svg",
  MySQL: "/tech-icons/mysql-original.svg",
  "Node.js": "/tech-icons/nodejs-original.svg",
  Python: "/tech-icons/python-original.svg",
  React: "/tech-icons/react-original.svg",
  "Spring Boot": "/tech-icons/spring-original.svg",
  TypeScript: "/tech-icons/typescript-original.svg",
  "Vue.js": "/tech-icons/vuejs-original.svg",
};
